### ISSUE TITLE
npm run develop error after first installation

### ISSUE THREAD

**Issue by YagoLopez** [adhrinae/ts-react-parcel#1]
```
> ts-react-parcel@1.0.0 develop C:\Users\UsuarioAurora\Documents\WebstormProjects\ts-react-parcel
> parcel ./src/index.html

Server running at http://localhost:1234
×  C:\Users\UsuarioAurora\Documents\WebstormProjects\ts-react-parcel\src\index.html: 'super' keyword unexpected here
SyntaxError: Unexpected identifier
      return yield super.parse(_this.contents);
                   ^^^^^
SyntaxError: 'super' keyword unexpected here
    at NativeCompileCache._moduleCompile (C:\Users\UsuarioAurora\Documents\WebstormProjects\ts-react-parcel\node_modules\v8-compil
e-cache\v8-compile-cache.js:226:18)
    at Module._compile (C:\Users\UsuarioAurora\Documents\WebstormProjects\ts-react-parcel\node_modules\v8-compile-cache\v8-compile
-cache.js:172:36)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (C:\Users\UsuarioAurora\Documents\WebstormProjects\ts-react-parcel\node_modules\v8-compile-cache\v8-compile-cache.j
s:159:20)
    at Parser.findParser (C:\Users\UsuarioAurora\Documents\WebstormProjects\ts-react-parcel\node_modules\parcel-bundler\lib\Parser
.js:59:45)
    at Parser.getAsset (C:\Users\UsuarioAurora\Documents\WebstormProjects\ts-react-parcel\node_modules\parcel-bundler\lib\Parser.j
s:66:22)
```

**Comment by adhrinae** [comment]
I'm sorry but it looks like there's a conflict between `parcel-bundler` and your local development environment.

- Which version of Node.js are you using? Are you using Node.js earlier than version 8?
- Have you tried to update the `parcel-bundler`(`npm install -D parcel-bundler`)?
- I assume you're using WebStorm, then have you checked your WebStorm's Node.js settings?

**Small Tip:**  Please provide the details of your situation when you report any errors for the others.

**Comment by YagoLopez** [comment]
@emaren84 thanks for your quick response. Probably you are rigth about node version. I'm in v6.10.0. I'll try to update and will report here.

**Comment by YagoLopez** [comment]
Node version was the problem indeed. Thank you for pointing me in the right direction. This tech stack looks very efficient. (I hate configuring webpack a bit 😄 ) Gonna leave a star in the repo. I think it deserve it.
